version: "3"
services:
  eventservice:
    environment:
      - TF_VAR_access_key=${AWS_ACCESS_KEY_ID}
      - TF_VAR_secret_key=${AWS_SECRET_ACCESS_KEY}
      - TF_VAR_gh_token=${TF_VAR_gh_token}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    build:
      context: . #Dir for Compose to build
    env_file:
      - ./.env
    # Portmapping
    ports:
      - "8000:80"
    volumes: 
    # Copy changes to the image in real-time.
      - ./adminservice:/adminservice
    