version: "3"
services:
  eventservice:
    environment:
      - TF_VAR_access_key=${TF_VAR_access_key}
      - TF_VAR_secret_key=${TF_VAR_secret_key}
      - TF_VAR_gh_token=${TF_VAR_gh_token}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    build:
      context: . #Dir for Compose to build
    env_file:
      - ./.env
    # Portmapping
    ports:
      - "8000:80"
    volumes: 
    # Copy changes to the image in real-time.
      - ./adminservice:/adminservice
    