version: "3"
services:
  eventservice:
    #environment:
    #  - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
    #  - AWS_SECRET=${AWS_SECRET}
    build:
      context: . #Dir for Compose to build
    env_file:
      - ./.env
    # Portmapping
    ports:
      - "80:80"
    volumes: 
    # Copy changes to the image in real-time.
      - ./adminservice:/adminservice
    